### ISSUE TITLE
in node

### ISSUE THREAD

**Issue by rikki78** [estbeetoo/node-red-contrib-marantz-http#1]
Hi 
Could you finish the in node? Or give some hints so I can finish it myself?
Thanks

**Comment by aborovsky** [comment]
Hi, @rikki78! PRs are welcomed! How can i help you to finish "in-node" yourself?

**Comment by rikki78** [comment]
Hi thanks for your reply
I've created two pull requests. To finish the in-node, all I need to know is on which event the state can be injected in the flows. I don't know where to start exactly. Perhaps you can point me in the right direction...

**Comment by rikki78** [comment]
Hi @aborovsky 
Could you give me some hints how to finish the node-in node?

edit: to be more exact, when will the node.receiveNotification be called? 
https://github.com/estbeetoo/node-red-contrib-marantz-http/blob/master/marantz_http.js#L322

**Comment by aborovsky** [comment]
@rikki78 Current node use marantz-avr as driver library.
According to it's sources there is not way to receive notifications automatically on some event happens: https://github.com/estbeetoo/marantz-avr/blob/master/lib/avreciever.js

I propose to implement polling logic:

1. Bind a listener after driver connected: `fsm.on('connected', onConnected)`
1. Inside of `onConnected` start poll interval: `const statusPoll = setInterval(requestStatus, 1000) `
1. inside of `requestStatus(...)` call `const requestStatusPromise = fsm.connection.requestStatus(...);`
1. `connection.requestStatus(...)` returns Promise, so do that: `requestStatusPromise.then(status => node.receiveNotification(status))`
1. also, don't forget to bind a listener on connection lost: `fsm.on('disconnected', ()=> clearInterval(statusPoll))`
