### ISSUE TITLE
Get status from AVR

### ISSUE THREAD

**Issue by rikki78** [estbeetoo/node-red-contrib-marantz-http#6]
Hi
I noticed that in your similar plugin for Denon, there was [an issue](https://github.com/estbeetoo/node-red-contrib-denon/issues/5) regarding to getting the status from the AVR. Can you indicate how this can be done for the Marantz plugin? 
So I would like to request/receive the actual status from the AVR.

Thanks

**Comment by aborovsky** [comment]
It's related to https://github.com/estbeetoo/node-red-contrib-marantz-http/issues/1
